### ISSUE TITLE
DBManager.OpenDB: Generate DBRef from filepath

### ISSUE THREAD

**Issue by NikolajLindberg** [stts-se/pronlex#34]
https://github.com/stts-se/pronlex/blob/8efdd68ee34856f84fd38e694fdacc1cfb736309/dbapi/db_manager.go#L81

It appears redundant to give both db name and path, since the name is the same as the file name minus extension.

**Comment by HannaLindgren** [comment]
OpenDB method signature has changed, so the issue is not longer valid.
