### ISSUE TITLE
Links from lexserver/lexicon page are missing lexserver/ path-prefix

### ISSUE THREAD

**Issue by lokal-profil** [stts-se/pronlex#56]
Visiting e.g. https://wikispeech-tts-dev.wmflabs.org/lexserver/lexicon/ you see that the list link goes to[ /lexicon/list]( https://wikispeech-tts-dev.wmflabs.org/lexicon/list), it should be pointing to [lexserver/lexicon/list](https://wikispeech-tts-dev.wmflabs.org/lexserver/lexicon/list)

https://github.com/stts-se/pronlex/blob/3360e692965fe020681bf99e8e68c5541587b3e3/lexserver/lexserver.go#L839
I believe changing `"/lexicon"` to `"lexserver/lexicon"` would probably fix it but since this would need to have to be repeated for each subrouter and since the lexserver prefix was probably determined by 
[wikispeech_server/wikispeech.py#L793](https://github.com/stts-se/wikispeech-server/blob/d378c8e72836f658522414d8c31b4f67da24ebf0/wikispeech_server/wikispeech.py#L793) I'm guessing that the needed change is in how `rout` is defined.

**Comment by HannaLindgren** [comment]
Moved to Phabricator: https://phabricator.wikimedia.org/T275127
